// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.Networking;

namespace AssemblyCSharp
{
	public class LPC_GameServer:MonoBehaviour
	{
		private LPC_GameServer ()
		{
		}

		private static GameObject s_LPC_GameServer_object;
		private static LPC_GameServer s_LPC_GameServer = null;
		private static NetworkView s_LPC_NetworkView = null;

		public static LPC_GameServer DefaultServer
		{
			get{
				if (s_LPC_GameServer == null) 
				{
					s_LPC_GameServer_object = new GameObject("DefaultServer");
					s_LPC_GameServer = s_LPC_GameServer_object.AddComponent<LPC_GameServer>();
					s_LPC_NetworkView = s_LPC_GameServer_object.AddComponent<NetworkView>();
				}

				return s_LPC_GameServer;
			}
		}

		private static NetworkView DefalutNetworkView
		{
			get{
				return s_LPC_NetworkView;
			}
		}


		/// <summary>
		/// init server...
		/// </summary>
		/// <param name="ip">Ip.</param>
		/// <param name="port">Port.</param>
		public bool InitServer(string ip,int port)
		{
			//set property
			MasterServer.ipAddress = ip;
			MasterServer.port = port;

			return true;
		}

		/// <summary>
		/// Starts the server.
		/// </summary>
		/// <returns><c>true</c>, if server was started, <c>false</c> otherwise.</returns>
		public bool StartServer()
		{
			//start...
			Network.InitializeServer(1000,25000,!Network.HavePublicAddress());

			return true;
		}

        public bool RegisterHost(string gameType, string gameName)
        {
            //register a game
            MasterServer.RegisterHost(gameType, gameName);

            return true;
        }

		public delegate void RequestRoomComplete(HostData[] list);
		private RequestRoomComplete complete_block = null;
		public RequestRoomComplete CompleteBlock{
			set{
				complete_block = value;
			}
			get{
				return complete_block;
			}
		}

		public void StartRequestRoom(RequestRoomComplete block, string gameTypeName)
		{
			LPC_GameServer.DefaultServer.CompleteBlock = block;

			MasterServer.RequestHostList(gameTypeName);
		}


		public delegate void JoinHostRoomDelegate(int state);

		private JoinHostRoomDelegate join_delegate = null;
		public void JoinHostRoom(HostData room,JoinHostRoomDelegate block)
		{
			this.join_delegate = block;

			NetworkConnectionError error = Network.Connect(room.ip[0],room.port);

			DebugManager.DefaultManager.Log(error);
		}

		public void SendGameMessage(string message)
		{
			LPC_GameServer.DefalutNetworkView.RPC("RemoteReceiveMessage",RPCMode.All,message);
		}

		[RPC]
		public void RemoteReceiveMessage(string message)
		{
			DebugManager.DefaultManager.Log(message);
		}

		#region Behaviour Actions


		/// <summary>
		/// some event notification from master server
		/// </summary>
		/// <param name="ev">Ev.</param>
		public void OnMasterServerEvent(MasterServerEvent ev)
		{
			switch (ev) {
			case MasterServerEvent.RegistrationSucceeded:
			{
				break;
			}
				
			case MasterServerEvent.RegistrationFailedNoServer:
			{
				break;
			}
			case MasterServerEvent.RegistrationFailedGameType:
			{
				break;
			}
			case MasterServerEvent.RegistrationFailedGameName:
			{
				break;
			}
			case MasterServerEvent.HostListReceived:
			{
				LPC_GameServer.DefaultServer.CompleteBlock(MasterServer.PollHostList());
				break;
			}
			default:
				break;
			}

		}


		public void OnPlayerConnected(NetworkPlayer player)
		{

		}

		public void OnConnectedToServer()
		{
			this.join_delegate(0);
			DebugManager.DefaultManager.Log("OnConnectedToServer");
		}

		#endregion
	}
}






